[api_details]
#Enter API key as provided during applicaiton registration. See https://dev.freebox.fr/sdk/os/login/# for more details
api_token = XXXXXXXXXXXXXXXXX
#API versions:
#V4 for Freebox Revolution
#V6 for Freebox Mini
#V8 for Freebox Delta
api_version = v8
[cert_details]
#File containing full chain certificate for mafreebox.freebox.fr. File provided at https://github.com/doktoil-makresh/xymon-plugins/blob/master/xymon-freebox_v6/mafreebox_fullchain.pem should do the job
mafreebox_fullchain = /etc/xymon/mafreebox_fullchain.pem
cert_check = True
[app_details]
#App name as used during registration
app_id= fr.freebox.monitoring
#This is the name that will appear in Freebox server applications access menu and on display as well
app_name = Xymon Client
#Self explanatory
app_version = 1
#This is the hostname of the device, displayed in Freebox server applications access menu
device_name = walter
[monitoring_details]
#Values and details can be found here: https://dev.freebox.fr/sdk/os/# 
## Disk status
disk_expected_status = active
#Set the name of your disk attached to Freebox Server
disk_expected_name = 
#Expected download available (in bit per second)
bandwidth_down_min = 5000000000
#Expected download available (in bit per second)
bandwidth_up_min = 900000000
#Decide the uptime minimum value in seconds
uptime_min = 300 

##If using API v4 & V6, set the following values:
#Define the fan minimum rotation per minutes
fan_rpm_min = 1700 
#CPU M maximum temperature
temp_cpum_max = 70
#CPU B maximum temperature
temp_cpub_max = 85 
#Switch maximum temperature
temp_switch_max = 60 

##There are many subtles differences between Freeboxes running API v8.
#Please set the specific settings for your model:
##If using API v8, set the following values:
#Define the fans minimum rotation per minutes (se to -1 if expecting 0)
fan0_rpm_min = -1
#Define temperature probe max temperature
temp_t1_max = 52

##Specifics to Freebox Delta:
# 2 fans
# 2 CPU temperature probes
# 3 undocumented temperatures probes
# 1 access-point chip temperature probe
fan1_rpm_min = 1400
#Set the maximum temperatures for undocumented sensors
temp_t2_max = 52
temp_t3_max = 52
##Freebox Delta
#Set the maximum temeratures for CPU
temp_cpu_cp_master_max = 85
temp_cpu_cp_slave_max = 85
#Set the maximum temeratures for access point chip
temp_cpu_ap_max = 72

##Specifics to Freebox POP-S:
# 1 fan
# 1 CPU temperature probe
# 1 undocumented temperature probe
temp_cpu_max = 85
